Fix: Downgrade prompt-toolkit (#1473)
## Description

Downgrade prompt-toolkit
[3.0.52](https://github.com/prompt-toolkit/python-prompt-toolkit/releases/tag/3.0.52)
->
[3.0.51](https://github.com/prompt-toolkit/python-prompt-toolkit/releases/tag/3.0.51)

## Motivation

Was causing bug in questionary and thus in `ato create part`

```
ato create part
[12:03:40] INFO     Using project /home/user/MyData/pcb-ato                                                                         
? Search for a component (Part Number or LCSC ID): C2927038
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━┓
┃ Manufacturer ┃ Part Number    ┃ Description ┃ Supplier ID ┃ Stock ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━┩
│ DEALON       │ USB-TYPE-C-018 │             │ C2927038    │ 18389 │
└──────────────┴────────────────┴─────────────┴─────────────┴───────┘
[12:04:16] ERROR    Uncaught compiler exception                                                                                         
                    ╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
                    │ /home/user/.local/share/uv/python/cpython-3.13.6-linux-x86_64-gnu/lib/python3.13/contextlib.py:85 in inner   │
                    │                                                                                                                  │
                    │    82 │   │   @wraps(func)                                                                                       │
                    │    83 │   │   def inner(*args, **kwds):                                                                          │
                    │    84 │   │   │   with self._recreate_cm():                                                                      │
                    │ ❱  85 │   │   │   │   return func(*args, **kwds)                                                                 │
                    │    86 │   │   return inner                                                                                       │
                    │    87                                                                                                            │
                    │    88                                                                                                            │
                    │                                                                                                                  │
                    │ /home/user/.cache/uv/archive-v0/HfCMWV6-JtjfavfsiVyXP/lib/python3.13/site-packages/atopile/cli/create.py:828 │
                    │ in part                                                                                                          │
                    │                                                                                                                  │
                    │   825 │   │   │   │   for component in components                                                                │
                    │   826 │   │   │   ] + [{"name": "Search again...", "value": None}]                                               │
                    │   827 │   │   │                                                                                                  │
                    │ ❱ 828 │   │   │   component = questionary.select(                                                                │
                    │   829 │   │   │   │   "Select a component", choices=choices                                                      │
                    │   830 │   │   │   ).unsafe_ask()                                                                                 │
                    │   831                                                                                                            │
                    │                                                                                                                  │
                    │ /home/user/.cache/uv/archive-v0/HfCMWV6-JtjfavfsiVyXP/lib/python3.13/site-packages/questionary/prompts/selec │
                    │ t.py:205 in select                                                                                               │
                    │                                                                                                                  │
                    │   202 │   │                                                                                                      │
                    │   203 │   │   return tokens                                                                                      │
                    │   204 │                                                                                                          │
                    │ ❱ 205 │   layout = common.create_inquirer_layout(ic, get_prompt_tokens, **kwargs)                                │
                    │   206 │                                                                                                          │
                    │   207 │   bindings = KeyBindings()                                                                               │
                    │   208                                                                                                            │
                    │                                                                                                                  │
                    │ /home/user/.cache/uv/archive-v0/HfCMWV6-JtjfavfsiVyXP/lib/python3.13/site-packages/questionary/prompts/commo │
                    │ n.py:611 in create_inquirer_layout                                                                               │
                    │                                                                                                                  │
                    │   608 │   ps: PromptSession = PromptSession(                                                                     │
                    │   609 │   │   get_prompt_tokens, reserve_space_for_menu=0, **kwargs                                              │
                    │   610 │   )                                                                                                      │
                    │ ❱ 611 │   _fix_unecessary_blank_lines(ps)                                                                        │
                    │   612 │                                                                                                          │
                    │   613 │   @Condition                                                                                             │
                    │   614 │   def has_search_string():                                                                               │
                    │                                                                                                                  │
                    │ /home/user/.cache/uv/archive-v0/HfCMWV6-JtjfavfsiVyXP/lib/python3.13/site-packages/questionary/prompts/commo │
                    │ n.py:591 in _fix_unecessary_blank_lines                                                                          │
                    │                                                                                                                  │
                    │   588 │   default_container = ps.layout.container                                                                │
                    │   589 │                                                                                                          │
                    │   590 │   default_buffer_window = (                                                                              │
                    │ ❱ 591 │   │   default_container.get_children()[0].content.get_children()[1].content  # type:                     │
                    │       ignore[attr-defined]                                                                                       │
                    │   592 │   )                                                                                                      │
                    │   593 │                                                                                                          │
                    │   594 │   assert isinstance(default_buffer_window, Window)                                                       │
                    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    AttributeError: 'VSplit' object has no attribute 'content' 
```